### ISSUE TITLE
Small Typo: "to do" should be "to"

### ISSUE THREAD

**Issue by js336rice** [CEVE-421-521/ceve-421-521.github.io#1]
https://github.com/CEVE-421-521/lab-02/blob/6b413cda102f0ee5a464898426383fd749ec5356/index.qmd#L332

"use the @select function to do select the columns we want" should be "use the @select function to select the columns we want"

**Comment by js336rice** [comment]
Pull request is visible in the Lab 2 repository along with an issue identical to this one that I made in that repository.  It took me a minute to figure out how the separate repositories for labs thing works.

**Comment by jdossgollin** [comment]
Great work

**Comment by js336rice** [comment]
Thank you!
