### ISSUE TITLE
Policy Search Fix

### ISSUE THREAD

**Issue by LNguyen333** [CEVE-421-521/ceve-421-521.github.io#18]
https://github.com/CEVE-421-521/ceve-421-521.github.io/blob/e8322f6dd1e47f57e82e769c36e81900ee676db1/lectures/07-policy-search.qmd#L128C22-L128C39

discontinuitites -> discontinuities

**Comment by jdossgollin** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
