### ISSUE TITLE
The syllabus's links to Canvas and the course website are broken

### ISSUE THREAD

**Issue by js336rice** [CEVE-421-521/ceve-421-521.github.io#2]
https://github.com/CEVE-421-521/ceve-421-521.github.io/blob/ee6cd5163a9dca970ee07d1b1737ab5951ee0a35/syllabus.qmd#L92

I've looked at the code and I'm honestly not sure why these links aren't working?  But both of them return Page Not Found errors.  I'm going to try and link the websites via their raw URLs instead of the variables currently being used and hope that fixes it.

**Comment by jdossgollin** [comment]
Good catch, fixed by f75cd9757b68bebcb1d5c2561d1c1588d8c91295
