### ISSUE TITLE
Deep Uncertainty Fix 1

### ISSUE THREAD

**Issue by LNguyen333** [CEVE-421-521/ceve-421-521.github.io#23]
https://github.com/CEVE-421-521/ceve-421-521.github.io/blob/9b903729e9bf1842950111f27014b226bd170aae/lectures/11-deep-uncertainty.qmd#L57

weight-> weigh

**Comment by jdossgollin** [comment]
I don't think this is wrong, using weight as a verb as in "assign a weight to"

https://www.merriam-webster.com/dictionary/weight#dictionary-entry-2 "to assign a statistical weight to"
