### ISSUE TITLE
Typo (lecture 1, slide 29/43)

### ISSUE THREAD

**Issue by AnnaD16** [CEVE-421-521/ceve-421-521.github.io#4]
https://github.com/CEVE-421-521/ceve-421-521.github.io/blob/e1da5671903933c4ca1a732ea606fef58041d422/lectures/01-intro-class-topic.qmd#L270C1-L270C18

The word "examps" in this line should be corrected to "exams"

**Comment by AnnaD16** [comment]
I am having trouble finding how to make a pull request for this...

**Comment by jdossgollin** [comment]
Great, fixed it! +1
