### ISSUE TITLE
Formatting issue (lecture 2, slide 9/11)

### ISSUE THREAD

**Issue by AnnaD16** [CEVE-421-521/ceve-421-521.github.io#7]
https://github.com/CEVE-421-521/ceve-421-521.github.io/blob/a6b4fbb8204d3c24866656241d9ed68f31cb7de9/lectures/02-climate-hazard.qmd#L79

The word "observations" has a strike through, and there needs to be a space between it and the next word.

**Comment by jdossgollin** [comment]
I can't quite remember what I was going for. Certainly not quite this! +1
